FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y python3-pip python3-dev libpq-dev nano \
    && ln -s /usr/bin/python3 /usr/local/bin/python \
    && pip3 install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN chown -R root:root /app && chmod 755 -R /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

CMD ["sh", "-c", "python manage.py collectstatic --no-input; python manage.py migrate; gunicorn basalt_simple_wallet.wsgi -b :8000 --timeout 600 --reload & celery -A basalt_simple_wallet worker --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info --uid=nobody --gid=nogroup"]
